networks:
  e-jadwal-network:
    driver: bridge

services:
  app:
    build: .
    container_name: e-jadwal_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=${MONGO_URI}
    networks:
      - e-jadwal-network

volumes:
  mongo-data:
    driver: local
